#!/usr/bin/env python3
"""Regenerate docs/assets/player_stats.js from docs/season.html.

docs/season.html's "Player Season Stats -- Senior Matches" table (id
"player-stats") is the only source of truth for per-player season Apps/G/A/
MOTM/Rtg -- there is no JSON equivalent, it's hand-maintained match by match.
This script parses that table and emits a small generated lookup so the
homepage Squad Spotlight can show a featured player's real season goals,
assists and average rating without duplicating the numbers by hand (which
would go stale the moment the next match is logged).

Senior matches only, matching the table's own scope -- youth academy players
have no rows here and none are generated, which is intentional: the homepage
Next Generation section never shows season stats.

Run this after any session that updates docs/season.html's Player Season
Stats table (i.e. any match session, per the Match Submission Checklist in
CLAUDE.md).
"""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEASON_HTML = ROOT / "docs" / "season.html"
OUT = ROOT / "docs" / "assets" / "player_stats.js"

ROW_RE = re.compile(
    r'<div class="stats-row">\s*'
    r'<div><div class="s-name">(?P<name>.*?)</div><div class="s-pos">(?P<pos>.*?)</div></div>\s*'
    r'<span class="s-num">(?P<apps>\d+)</span>\s*'
    r'<span class="s-num(?: highlight)?">(?P<goals>\d+)</span>\s*'
    r'<span class="s-num(?: highlight)?">(?P<assists>\d+)</span>\s*'
    r'<span class="s-motm">(?P<motm>.*?)</span>\s*'
    r'<span class="s-rating">(?P<rating>[\d.]+)</span>',
    re.S,
)


def extract_table(html_text):
    marker = 'id="player-stats"'
    start = html_text.find(marker)
    if start == -1:
        raise SystemExit('Could not find id="player-stats" section in docs/season.html')
    end = html_text.find('<div class="footer">', start)
    if end == -1:
        end = len(html_text)
    return html_text[start:end]


def main():
    text = SEASON_HTML.read_text(encoding="utf-8")
    table_html = extract_table(text)

    players = {}
    for m in ROW_RE.finditer(table_html):
        name = html.unescape(m.group("name")).strip()
        players[name] = {
            "position": html.unescape(m.group("pos")).strip(),
            "apps": int(m.group("apps")),
            "goals": int(m.group("goals")),
            "assists": int(m.group("assists")),
            "rating": float(m.group("rating")),
        }

    if not players:
        raise SystemExit("Parsed zero player rows -- season.html markup may have changed; check ROW_RE.")

    body = (
        "/* GENERATED by scripts/sync_home_player_stats.py -- do not hand-edit.\n"
        "   Source: docs/season.html's Player Season Stats (Senior Matches) table.\n"
        "   Keyed by the abbreviated \"F. Lastname\" form used in that table.\n"
        "   Re-run after any session that updates season.html's player stats. */\n"
        "const PLAYER_SEASON_STATS = " + json.dumps(players, indent=2, ensure_ascii=False) + ";\n"
    )
    OUT.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(players)} players)")


if __name__ == "__main__":
    main()
