#!/usr/bin/env python3
"""Regenerates docs/assets/submit_data.js from wrexham_squad.csv,
youth_academy.csv, and season_log.json's "fixtures" array.

Run this whenever wrexham_squad.csv or youth_academy.csv changes (so the
Attribute Editor on docs/submit.html shows current values instead of stale
ones), or whenever a Premier League match is logged in season_log.json (so
the played fixture drops out of the schedule picker).
"""
import csv
import json
import re
import time
import unicodedata

# Regular starting XI — used to default the Player Stats "Status" radio to
# Started on docs/submit.html. Matched against the CSV row's surname
# (accent-insensitive). Update this set by hand when the first-choice XI
# changes; there's no other source for it.
STARTERS = {
    'sauer', 'okonkwo', 'heaven', 'gutierrez', 'doyle', 'mokio',
    'cacace', 'ngumoha', 'fruk', 'amrizi', 'bobadilla',
}


def _normalize(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn'
    ).lower()


ATTR_KEYS = [
    'Position', 'Age', 'Height', 'Weight', 'Pref_Foot', 'Squad_Role',
    'Contract_Length', 'Status', 'OVR', 'Pace', 'Shooting', 'Passing',
    'Dribbling', 'Defending', 'Physical', 'Potential',
    'Acceleration', 'Agility', 'Balance', 'Jumping', 'Sprint_Speed',
    'Stamina', 'Strength', 'Aggression', 'Att_Position', 'Composure',
    'Interceptions', 'Reactions', 'Vision',
    'Ball_Control', 'Crossing', 'Curve', 'Def_Aware', 'Dribbling_Tech',
    'FK_Acc', 'Finishing', 'Heading_Acc', 'Long_Pass', 'Long_Shots',
    'Penalties', 'Short_Pass', 'Shot_Power', 'Slide_Tackle', 'Stand_Tackle',
    'Volleys', 'Skill_Moves', 'Weak_Foot', 'PlayStyles', 'Roles',
    'Wage', 'Market_Value', 'Development_Plan', 'Notes',
]


def load_roster(path, starters=None):
    with open(path, newline='', encoding='utf-8') as f:
        rows = list(csv.DictReader(f))
    names = []
    attrs = {}
    for row in rows:
        name = (row.get('Name') or '').strip()
        if not name:
            continue
        status = (row.get('Status') or '').strip()
        on_loan = status.lower().startswith('on loan')
        attrs[name] = {k: (row.get(k) or '').strip() for k in ATTR_KEYS}
        if on_loan:
            # On-loan players aren't training/playing with the first team —
            # exclude them from the submit sheet's dropdowns and stat tables
            # entirely rather than just graying them out.
            continue
        entry = {'name': name, 'pos': (row.get('Position') or '').strip()}
        if starters is not None:
            entry['starter'] = _normalize(name.split()[-1]) in starters
        names.append(entry)
    names.sort(key=lambda p: p['name'].split()[0].lower())
    return names, attrs


def load_pl_fixtures(path):
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    played_dates = {
        m['date'] for m in d.get('matches', [])
        if m.get('competition') == 'Premier League'
    }
    fixtures = [
        {'date': fx['date'], 'opponent': fx['opponent'], 'home': fx['home']}
        for fx in d.get('fixtures', [])
        if fx.get('competition') == 'Premier League' and fx['date'] not in played_dates
    ]
    fixtures.sort(key=lambda fx: fx['date'])
    return fixtures


def main():
    senior_names, senior_attrs = load_roster('wrexham_squad.csv', starters=STARTERS)
    academy_names, academy_attrs = load_roster('youth_academy.csv')
    attrs = {}
    attrs.update(senior_attrs)
    attrs.update(academy_attrs)
    pl_fixtures = load_pl_fixtures('season_log.json')

    out = []
    out.append('// AUTO-GENERATED by scripts/sync_submit_roster.py — do not hand-edit.')
    out.append('// Regenerate after any wrexham_squad.csv / youth_academy.csv change,')
    out.append('// or after a Premier League match is added to season_log.json.')
    out.append('var ROSTER_SENIOR = ' + json.dumps(senior_names, ensure_ascii=False, indent=2) + ';')
    out.append('var ROSTER_ACADEMY = ' + json.dumps(academy_names, ensure_ascii=False, indent=2) + ';')
    out.append('var ROSTER_ATTR_DATA = ' + json.dumps(attrs, ensure_ascii=False, indent=2) + ';')
    out.append('var PL_FIXTURES = ' + json.dumps(pl_fixtures, ensure_ascii=False, indent=2) + ';')

    with open('docs/assets/submit_data.js', 'w', encoding='utf-8') as f:
        f.write('\n'.join(out) + '\n')

    # Cache-bust the script tag so a service-worker cache (or plain browser
    # cache) can never mask a roster update on submit.html.
    version = int(time.time())
    with open('docs/submit.html', encoding='utf-8') as f:
        html = f.read()
    html, n = re.subn(
        r'assets/submit_data\.js(\?v=\d+)?"',
        f'assets/submit_data.js?v={version}"',
        html,
    )
    if n != 1:
        raise RuntimeError(f'expected exactly 1 submit_data.js script tag in submit.html, found {n}')
    with open('docs/submit.html', 'w', encoding='utf-8') as f:
        f.write(html)

    print(f'Wrote docs/assets/submit_data.js — {len(senior_names)} senior, '
          f'{len(academy_names)} academy, {len(pl_fixtures)} remaining PL fixtures.')


if __name__ == '__main__':
    main()
